dist: trusty
sudo: required
language: c
cache:
  apt: true
  directories:
  - $HOME/.opam
  - $HOME/bin
  
addons:
  apt:
    sources:
    - avsm
 
env:
  global:
  - NJOBS=2
  - COMPILER="4.06.1"
  matrix:
  - COQ_VER="8.10.2" EQUATIONS_VER="1.2+8.10" METACOQ_VER="1.0~alpha1+8.10"
  
install:
- curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh > install.sh
- export PATH=$HOME/bin:$PATH
- which opam || (rm -rf $HOME/.opam; echo $HOME/bin | sudo sh install.sh --no-backup; opam init --disable-sandboxing -j ${NJOBS} --compiler=${COMPILER} -n -y)
- opam --version
- opam update
- opam init -j ${NJOBS} -n -y --compiler=$COMPILER
- opam switch set ${COMPILER}
- eval $(opam config env)
- opam config list
- opam repo add coq-released https://coq.inria.fr/opam/released || echo "coq-released registered"
- opam install -j ${NJOBS} -y coq.${COQ_VER} coq-equations.${EQUATIONS_VER} coq-metacoq-template.${METACOQ_VER} coq-metacoq-checker.${METACOQ_VER}
- opam list

script:
 - make -j ${NJOBS} all
