name: CI

on: [push, pull_request]

env:
  OCAML_VERSION: 4.07.1+flambda
  CACHE_KEY: opam-flambda-8.15-newmetacoq-${{github.base_ref}}-${{github.ref}} 
jobs:
  build-deps:
    runs-on: ubuntu-latest
    steps:
    - name: Try to restore build cache
      id: cache
      uses: actions/cache@v2
      with:
        path: "~/.opam"
        key: ${{env.CACHE_KEY}}
        restore-keys: |
          opam-flambda-8.15-gitnewmetacoq--refs/heads/${{github.base_ref}}

    - name: Install OCaml
      if: steps.cache.outputs.cache-hit != 'true'
      uses: avsm/setup-ocaml@v1
      with:
        ocaml-version: ${{env.OCAML_VERSION}}

    - name: Checkout code
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Build dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        opam repo add coq-released https://coq.inria.fr/opam/released
        opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev
        opam update
        opam upgrade
        opam pin add -n -y -k git coq-metacoq-template.dev+8.15 "https://github.com/MetaCoq/metacoq.git#9493bb6"
        opam pin add -n -y -k git coq-smpl.8.15 "https://github.com/uds-psl/smpl.git#54a001b79"
        opam install . --deps-only --with-doc --with-test 
        opam list --installed
  

  build-full:
    needs: build-deps
    runs-on: ubuntu-latest
    steps:
    - name: Restore build cache
      id: cache
      uses: actions/cache@v2
      with:
        path: "~/.opam"
        key: ${{env.CACHE_KEY}}
    - name: Check sucess of cache restoration
      if: steps.cache.outputs.cache-hit != 'true'
      run: exit
    
    - name: Install OCaml
      uses: avsm/setup-ocaml@v1
      with:
        ocaml-version: ${{env.OCAML_VERSION}}
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Build full (vo)
      run: opam exec -- make -j 2 all TIMED=1


  build-fast:
    needs: build-deps
    runs-on: ubuntu-latest
    steps:
    - name: Restore build cache
      id: cache
      uses: actions/cache@v2
      with:
        path: "~/.opam"
        key: ${{env.CACHE_KEY}}
    - name: Check sucess of cache restoration
      if: steps.cache.outputs.cache-hit != 'true'
      run: exit

    - name: Install OCaml
      uses: avsm/setup-ocaml@v1
      with:
        ocaml-version: ${{env.OCAML_VERSION}}
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Build interfaces (vos)
      run: opam exec -- make -j 2 vos TIMED=1
    - name: Check interfaces (vok)
      run: opam exec -- make -j 2 vok TIMED=1
